### ISSUE TITLE
Build and generate website with java tools

### ISSUE THREAD

**Issue by ajbaird** [BioGearsEngine/core#43]
- Use the appropriate java classes to create the website 
- Demonstrate what each java class does and create a short document that details what they do 
- Work with programmers to update wiki article regarding website generation 
- Demonstrate that you have the website up and running

**Comment by Shashankjain12** [comment]
https://docs.google.com/document/d/1TcbdG4jRfgQ3UGW40xKMFsqiEpggR00JCWChbIU0XkQ/edit?usp=sharing

[BioGears_Java_Build.pdf](https://github.com/BioGearsEngine/core/files/4735356/BioGears_Java_Build.pdf)

@ajbaird  @LucasJMO  kindly look at that

**Tasks done while building the biogears website using java:-**

- [ ]  Used Java Classes to build the website

- [ ] Created and uploaded the short documentation of how to build the website and what those classes are doing respectively

- [ ] Website is up and running some screenshots are attached in that docx file which demonstrate the process and the website is running

**Task remaining now is:-**

- To update a wiki article

**Comment by StevenAWhite** [comment]
I think this issue is ready to close out.  @LucasJMO If you bring over the wiki articles from the branch close this issue and we will start using CMD2MD.java to track the python work.

**Comment by StevenAWhite** [comment]
-- Pull Request Accepted and Ready for Merge
